### ISSUE TITLE
Hi there!

### ISSUE THREAD

**Issue by sebaxakerhtc** [loicpirez/HackintoshConfig#1]
1) Thak you so mush!!!

840G1

ok, I have a 3 problems with this config: 
a) using ssdt, ssdt-1, ssdt-2 - loading MacOS veeeery sloooow. If I delete ssdt-2 - all is fine.
b) I replace display from TN 1600x900 to AH-IPS 1920x1080, and MacOS boot with artefacts, then I should to sleep my display and after it - all is fine, but it's not good :) else I can put 1600x900 and it's working nice but artefacts when booting apple image. IntelGraphicsFixup do not work(after replacing with new - no luck)
c) After sleep do not work camera

**Comment by loicpirez** [comment]
@sebaxakerhtc , thanks for your feedback!

a) Really ? This doesn't happen to me. Maybe our PC are differents models of G1?
b) I only changed resolution with DisplayPort and it work fine. Never used with lower resolution on internal display. Maybe you should try put verbose on boot instead of logo when you are with 1600x900?

I don't know for IntelGraphicsFixup and Camera I'm really sorry. 
You should ask to forums like InsanelyMac.

Good luck!

**Comment by sebaxakerhtc** [comment]
Anyway, thak you for config ;)

**Comment by sebaxakerhtc** [comment]
Oh, no. Its from mobile phone oneplus3t, android 8.1

вт, 10 окт. 2017 г., 17:29 Loïc P. <notifications@github.com>:
